@BASE_URL=http://localhost:4200/api
@INSERTED={{addtodo.response.body.id}}

##
GET {{BASE_URL}}/todos
###

# @name addtodo
POST {{BASE_URL}}/todos
Content-Type: application/json

{
    "userId": 1,
    "title": "geposted from REST Client",
    "completed": true
}
###
GET {{BASE_URL}}/todos/{{INSERTED}}

